### ISSUE TITLE
please upgrade to WSL2

### ISSUE THREAD

**Issue by hmidani-abdelilah** [DesktopECHO/xWSL#10]
not working with WSL2 and the package is old and conflicted    
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  xrdp
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/428 kB of archives.
After this operation, 65.5 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up libc6:amd64 (2.31-0ubuntu9) ...
sleep: cannot read realtime clock: Invalid argument
dpkg: error processing package libc6:amd64 (--configure):
 installed libc6:amd64 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 libc6:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
```

abdelilah@HMIDANI:/mnt/c/WINDOWS/system32$ sudo aptitude upgrade
The following packages will be upgraded:
  xrdp
The following partially installed packages will be configured:
  libc-bin libc6
1 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/428 kB of archives. After unpacking 65.5 kB will be used.
Do you want to continue? [Y/n/?] y
Setting up libc6:amd64 (2.31-0ubuntu9) ...
sleep: cannot read realtime clock: Invalid argument
dpkg: error processing package libc6:amd64 (--configure):
 installed libc6:amd64 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 libc6:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
Setting up libc6:amd64 (2.31-0ubuntu9) ...
sleep: cannot read realtime clock: Invalid argument
dpkg: error processing package libc6:amd64 (--configure):
 installed libc6:amd64 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent processing triggers for libc-bin:
 libc-bin depends on libc6 (>> 2.31); however:
  Package libc6:amd64 is not configured yet.
 libc-bin depends on libc6 (<< 2.32); however:
  Package libc6:amd64 is not configured yet.

dpkg: error processing package libc-bin (--configure):
 dependency problems - leaving triggers unprocessed
Errors were encountered while processing:
 libc6:amd64
 libc-bin


```

**Comment by DesktopECHO** [comment]
Hello,

> `Setting up libc6:amd64 (2.31-0ubuntu9) ...
sleep: cannot read realtime clock: Invalid argument`

The only way you would get this error is if your instance is still running in WSL1.

This command will tell you what version of WSL your instance is running:

`wsl -l -v`

Changing the instance to WSL2 does work without issue.
Stop the WSL service:
`sc stop lxssmanager`

Switch instance to WSL2
`wsl --set-version xWSL 2`

At this point you can unmark libc6:
`apt-mark unhold libc6`

**Comment by KushalSM** [comment]
Does this mean that we can upgrade from wsl 1 to wsl 2 without getting any errors?

**Comment by hmidani-abdelilah** [comment]
my WSL is version 2
```
PS C:\Users\abdelilah> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Stopped         2
```
i installed installed manually XFCE4 DE and XRDP and config but the audio is not work  and is work but the songs is not work  i try pulse audio windows and configure 
this is the link of pulse audio 

https://www.freedesktop.org/wiki/Software/PulseAudio/Ports/Windows/Support/ 

and this is the documentation link 

https://discourse.ubuntu.com/t/getting-sound-to-work-on-wsl2/11869
 
and this is version of UBUNTU WSL

```
PS C:\Users\abdelilah> ubuntu.exe

abdelilah@HMIDANI:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

abdelilah@HMIDANI:~$

```
this is Screenshots of WSL
 
[Screenshot-1](https://www.dropbox.com/s/n1pfvxmow1j2asi/Screenshot_2020-08-05_00-57-36.png?dl=0)

[Screenshot-2](https://www.dropbox.com/s/j2h0iypnfbaxp49/Screenshot_2020-08-05_00-58-03.png?dl=0)

**Comment by DesktopECHO** [comment]
I'm having difficulty understanding your message.

First you said there was a package conflict, now you're asking about something completely different - sound?

If you installed Ubuntu manually and are trying to get audio working this is not the place to ask.  Look [here](https://c-nergy.be/blog/?p=13655) for more info.

**Comment by DesktopECHO** [comment]
> Does this mean that we can upgrade from wsl 1 to wsl 2 without getting any errors?

Yes

**Comment by KushalSM** [comment]
Wow nice i will install it now and try it
