### ISSUE TITLE
Doesn't work, black screen, doesn't start

### ISSUE THREAD

**Issue by xpusostomos** [DesktopECHO/xWSL#11]
Latest Windows 10... WSL2, latest.
Followed the instructions, and when it came time to fire up RDP, black screen, nothing. SSH worked, albeit with error messages about permission denied reading /etc/profile

Tried rebooting, it didn't seem to start automatically as advertised. xwsl and ssh both fail to connect.

Tried to follow the gloriously informative instructions to "right click in task manager" (where??), but could not find anywhere interesting enough to click. There seemed no reference in there to xWSL.

The confidence you have that xWSL "just works" is commendable, but the lack of documentation about what on earth this thing is and how to debug it when it fails... not so much.

As far as I see, this project, even if working... would achieve very little that 5 minutes at the terminal, or a well crafted apt package could not, with the exception that I can't find any pre built xrdp audio plugin that works, and building it yourself isn't that easy. If you'd direct your attention to making that a downloadable apt, it would be better.

**Comment by KushalSM** [comment]
You will have to check the prebious closed issue to understand the reason for black screen.

Also would you like to tell us if you are trying to run xWSL with WSL 1 or 2 ???

**Comment by xpusostomos** [comment]
You can't blame me too much for having no clue since the bleeding thing doesn't work and is undocumented.
