### ISSUE TITLE
Cannot RDP in a second time

### ISSUE THREAD

**Issue by grubin667** [DesktopECHO/xWSL#14]
I already have a WSL 2 dev environment set up. I forked your repo and edited xWSL.cmd as recommended. Setup took forever but it all worked and was glorious. I then converted my xWSL machine to WSL 2 and went looking for the .rdp file, finally finding it buried down a couple layers. I opened it for edit and added "-xWSL.local" before the port. Tried to connect and it couldn't find it. I started the machine in terminal and tried again. Same thing. I reverted to WSL 1 and tried again with the same results. So I've never gotten it to work a second time. Here's my error from mstsc:
![image](https://user-images.githubusercontent.com/7352993/94321713-67b2c800-ff5e-11ea-8c5b-928deeb8bf68.png)
Can you help, please?
Jerry Rubin

**Comment by DesktopECHO** [comment]
Hi Jerry,

Did you run the Init scheduled task or set it to autostart at boot time?

Did you set a name for the distro or did you use the default? (xWSL)

Can you open a command prompt and try to ping the mDNS hostname? 

(ie: PING laptop-xWSL.local) <- Replace xWSL with your distro name.

If you switch back to WSL1 just use the regular hostname to connect.

FYI, the RDP connection file is copied to your desktop along with a copy of in the root of the distro install folder.

Installation takes about 15-25 minutes on a machine with broadband internet and an SSD drive.  A hard drive and/or slower internet will indeed take much longer.

Good luck and let me know how things go.
Regards,
D.

**Comment by grubin667** [comment]
Hi, Dan. Thanks for getting back to me. I'll answer completely when I get back to my "play" computer. WRT the RDP file on the desktop: nope, it's just down in the distro.
TTYL,
Jerry

**Comment by grubin667** [comment]
All is well. Although I had seen the cmd window that ends Select Runlevel..., I didn't realize I had to run `schtasks /run /tn xWSL` to open it again before double-clicking the rdp file. Now that I've done that, I'm back in. Next I'll switch back to WSL 2, but I'm sure I can get that to work. Probably.

Thanks, Dan. Nice work. And I hope you don't get any more close hurricane calls off Bermuda. Funny but with all the crap going on in the US, we don't even see weather news that's not in the US.

Jerry
