### ISSUE TITLE
user cannot be added: file not found at end of install script

### ISSUE THREAD

**Issue by tobidelbruck** [DesktopECHO/xWSL#15]
Looks really nice. After running install script, xfce starts up, but the selected username/password is not accepted.
At the end of script just after username/password prompt, there was (not very helpful) pair of warning messages "File not found".
Is there a default username/password to login as root?

This is on windows 10x64 that is up to date as of 18.10.2020 with WSL2 installed.
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

WSL Ubuntu 18.0-4 was already installed.

**Comment by KushalSM** [comment]
while installing the script.. the script will ask you to enter a username and a passsword that you will use

**Comment by KushalSM** [comment]
Remove the distro and try running the script again

**Comment by tobidelbruck** [comment]
Sorry, got the same problem:

Enter name of xWSL user: tobi
Enter password: **
The system cannot find the path specified.
The system cannot find the path specified.
SUCCESS: The scheduled task "xWSL" has successfully been created.

      Start: Sun 10/18/2020 @ 19:49:49.08
        End: Sun 10/18/2020 @ 20:05:57.11
   Packages: 910

  - xRDP Server listening on port 3399 and SSHd on port 3322.

  - Links for GUI and Console sessions have been placed on your desktop.

  - (Re)launch init from the Task Scheduler or by running the following command:
    schtasks /run /tn xWSL

 xWSL Installation Complete!  GUI will start in a few seconds...

----------------
I don't have time now, have to give up trying.  Thanks in any case. xWSL looks like it would be useful.

**Comment by DesktopECHO** [comment]
Hi There,

I have updated the script for better logging and made some fixes for file handling.  If you get an opportunity, re-try the install.  If you have any isssues you can send me the *.log files in the install folder.

Regards,
D.

**Comment by DesktopECHO** [comment]
> Packages: 910

Just noticed this.  Definitely a download failure somewhere, as you should have 911.  Just blow it away and redeploy.

**Comment by tobidelbruck** [comment]
Finally got a chance to try it out, and it works !!! :-)
Here is my log output, note that it still reports that the "The system cannot find the path specified" but the xfce environment boots and appears for me now. Really cool. Thank you.

```
 xWSL Installer

Enter a unique name for the distro or hit Enter to use default                                                          Keep the name simple, no space or underscore characters [xWSL]:                                                                                                                                                                                 Set custom DPI scale or hit Enter to use Windows value [96]:                                                            Port number for xRDP traffic or hit Enter to use default [3399]:                                                        Port number for SSHd traffic or hit Enter to use default [3322]:                                                        [Not recommended!] Type X to eXclude xWSL from Windows Defender:                                                        
Download and install "xWSL" to location "F:\tobi\xWSL\xWSL"

Installing Distro Base...

Add exclusions in Windows Defender if requested...

Download xWSL overlay...
Cloning into 'xWSL'...
remote: Enumerating objects: 148, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 148 (delta 15), reused 124 (delta 12), pack-reused 0
Receiving objects: 100% (148/148), 25.49 MiB | 18.85 MiB/s, done.
Resolving deltas: 100% (15/15), done.

Install repo packages, please wait...
Extracting templates from packages: 100%

Install Seamonkey Browser...
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: key B7B9C16F2667CA5C: public key "Daniel Folkinshteyn (Ubuntuzilla signing key) <nanotube@users.sourceforge.net>" imported
gpg: Total number processed: 1
gpg:               imported: 1

Install dependencies for desktop environments...
Extracting templates from packages: 100%

Install XFCE4...
Extracting templates from packages: 100%

Install Multimedia Components...
Extracting templates from packages: 100%

Cleaning up...
Adding user `xrdp' to group `ssl-cert' ...
Adding user xrdp to group ssl-cert
Done.


Enter name of xWSL user: tobi
Enter password: **
The system cannot find the path specified.
The system cannot find the path specified.
SUCCESS: The scheduled task "xWSL" has successfully been created.

      Start: Tue 11/03/2020 @ 16:17:36.75
        End: Tue 11/03/2020 @ 16:25:57.34
   Packages: 911

  - xRDP Server listening on port 3399 and SSHd on port 3322.

  - Links for GUI and Console sessions have been placed on your desktop.

  - (Re)launch init from the Task Scheduler or by running the following command:
    schtasks /run /tn xWSL

 xWSL Installation Complete!  GUI will start in a few seconds...
```

**Comment by DesktopECHO** [comment]
Hi Tobi, I'm happy to hear you're up and running.

Not so pleased about seeing this part though:

```Enter password: **```
```The system cannot find the path specified.```
```The system cannot find the path specified.```
```SUCCESS: The scheduled task "xWSL" has successfully been created.```

Can you please check your Windows Task Scheduler to see if there's an entry created for xWSL, and if you run the Scheduled Task manually, does it work?  

Are you using Windows in English or another language?  I've discovered that %USERPROFILE%\Desktop may be named differently for non-english users.  Is that the path to your desktop?  

I am making a few changes to the script today to better track where this error occurs.  Are you interested in re-running the script if you have time?  Multiple xWSL installs can co-exist without issue, you just have to set a different install path and different ports for RDP and SSH, so you don't have to blow-away an existing install if you don't want to.

Thanks,
D.

**Comment by tobidelbruck** [comment]
Sure, I can try it again, probably tomorrow after a deadline.

It would be great if the README.md includes specific uninstall process. 
I recall it is a bit tricky and the instructions are buried in a 
subfolder and require a special tool? (I might be thinking of another VM).

Thanks

**Comment by DesktopECHO** [comment]
Good idea, I will create an uninstaller to make this easier to look after... stay tuned.

**Comment by DesktopECHO** [comment]
Hello, 

I've updated the script to include an installer, and made a few other fix-ups to (hopefully) improve operation on non-English versions of Windows.  

Thanks,
D.

**Comment by tobidelbruck** [comment]
Whatever you did fixed it. After uninstall and reinstall, I now get this at end of script:
````
Install Multimedia Components...
Extracting templates from packages: 100%

Cleaning up...
Adding user `xrdp' to group `ssl-cert' ...
Adding user xrdp to group ssl-cert
Done.
````
BTW, in latest windows 10, the task scheduler has become extremely hard to find. It does not come up from start menu. You can start it from Run (windows R) with taskschd.msc.
In scheduler, I did see the leftover task xWSL after uninstall that runs the installed xWSL.bat file. This was from before the fix.
Anyhow it works fine now. 
Many thanks!

**Comment by DesktopECHO** [comment]
Excellent!  

Are you using a non-English version of Windows?  The old code assumed "Desktop" but now it queries the OS for the location of your Desktop folder is and runs with that instead.

The Uninstaller should work for non-admin users but you need to launch it as Administrator to remove the scheduled task.  

FYI, Task Scheduler is located in *Control Panel -> Administrative Tools -> Task Scheduler* which I agree is not at all user-friendly.  Usually I click Start and type *Sched* and **IF** Windows Search is working it will show up in the Start Menu.  

Thanks,
D.
