### ISSUE TITLE
Converting to WSL2 - See Wiki Page

### ISSUE THREAD

**Issue by dehade** [DesktopECHO/xWSL#17]
Hi,

i installed regarding your script.

Installation succeeded and xrdp was possible on wsl 1.

After that i converted to wsl 2.

I changed the .rdp connection, as you discribed in you documentation.

So similar from <windows hostname>:3333 to <windows hostname>-<distroname>.local.

But <windows hostname>-<distroname>.local is an unknown hostname.

Every time the distro is started, it gets a new ip address.

From windows host i can ping the ip.

But even the rdp connection directly using this ip does not work.

**Comment by DesktopECHO** [comment]
Hi.... so in your case you're using your instance name (By default it's ```xWSL```) instead of ```DistroName```, correct?

Run ```ip addr | grep eth0``` to get the IP address of your instance.  Try using that instead of a hostname in your RDP client to see if that works at least.  

In Windows, if you ```ping WindowsHostname-DistroName.local``` does it resolve?

**Comment by dehade** [comment]
Hi,

correct. I‘m using an own instance name. DistroName is a gereric placeholder for this.

I did some investigations and implemented a solution, so that it#s working now.

I‘m using windows 10 in version 20H2. LAN integration though wlan.

Why it#s not working seem to have serveral issues.

After converting wsl instance to version 2 first issue was, that a ping to WindowsHostname-DistroName.local does not work, because no ip is connected and result is unknown host. After each reboot of the wls 2 instance and the hyper-v vm it gets dynamic each time a new ip address. This ip address gets not bind to WindowsHostname-DistroName.local. So as address this does not work in mstc. This can be solved by using „localhost:port“ (in may case port = 3333). With this rdp access is possible.

Next issues was that still rdp with localhost:port does not work. Xrdp service was started automatically, but xrdp service seem not be reachable under the ip assinged to wsl 2 instance. If i do a restart of the xrdp service, after the restart rdp with localhost:port or ip address of the instance does work.

So here a rough summary what i did to get a solution:

I enabled the user, added at creating the instance, so that he can execute sudo commands without specifiying the root password (especially for startting/ restarting services).

I disablesd the automatic start of xrdp services.

I implemented a sh script for starting serveral services like xrdp, sshd, cron, dbus, ... with a check that they will be started, if not running.

I added a call to this script in .bashrc file.

I created a bat command file and vbs script for starting the wsl 2 instance and add it to the autostart of windows.

The wsl 2 instance is not the default instance.

With this the wsl 2 instance will be started and the xrdp, ... services correctly.

After that i can start the rdp session to the wsl 2 instance. Internet access from the wsl 2 instance and sound is working.

I had not yet the time to document all steps in detail.

But for me - with this i found a solution.

So for me issues are solved. Many thanks for providing the solution for creating the wsl 1 instance with rdp access and sound support.

I did get this not working before.

**Comment by dehade** [comment]
One info detail is missing. The reason for „ I enabled the user, added at creating the instance, so that he can execute sudo commands without specifiying the root password (especially for startting/ restarting services).“ is that the wsl 2 is started with a user and not the root user. The .bashrc file for the user has been extended with the mentioned sh script. The wsl 2 instance is started with wsl -d <instance> -u <user>.

**Comment by DesktopECHO** [comment]
Hi There, 

Glad to hear you got up and running.  I'll spin up another WSL2 instance in my lab and see if I can recreate your issue in 20H2, but ```WindowsHostname-DistroName.local``` should have resolved for you.  It worked for me in 20H1.  

This is 'magically' suppose to work because the xWSL instance has Avahi (Bonjour/multicast DNS) installed so the ```WindowsHostname-DistroName.local``` hostname resolves using mDNS.  

I'll report back and see if this still works for me in 20H2.  mDNS was my way to avoid all the steps you had to go through to accomplish the simple goal of reaching the xWSL VM.

Thanks,
D.

**Comment by DesktopECHO** [comment]
Hi - Update with my findings:

I installed xWSL on one of my lab machines "ENVY" with a clean install of Windows 10 20H2.
- Stopped WSL    ```wsl --shutdown```
- Converted the instance to WSL2    ```wsl --set-version xWSL 2```
- Restarted xWSL    ```schtasks /run /tn xWSL```
- Adjusted the RDP file saved to the desktop to now point at   ```ENVY-xWSL.local:3399``` 

This worked immediately!  Not sure what could be different with your machine setup but this does verify the conversion to WSL2 works as expected in Windows 10 20H2.  Screenshot below:

![image](https://user-images.githubusercontent.com/33142753/97915305-a854ec80-1d27-11eb-9dc1-24d75573aeec.png)

Kind Regards,
D.

**Comment by dehade** [comment]
Hi,

hard to identify the reasons. But  i can confirm now that it seems to be an issue with my pc and his windows history.

Correct the charme of your solution is, that all this workarounds roughly summarized by me has not to be implemented.

A main difference is that my pc has been updated with serveral windows versions, starting from 1909.

And there several hyper-v instances has been setup, executed and removed before.

Hyper-v and wsl 2 seem to be critical in handling network integration. In the web i found now serveral issues 
reported with network connections issues after converting from wsl 1 ro 2. 

I had today the chance to test it again on a fresh installed Windows 10 2004, updated to 20H2.

Installed is a windows 10 pro version with no other software. 

And there the wsl 1 installation of xWSL together with the conversion process from 
wsl 1 to wsl 2 as you documented worked without any issues.

**Comment by DesktopECHO** [comment]
Hi Dehade,

As you've noticed online, networking in WSL2 is a hot mess...
Thanks for testing this out and, and providing the push to better document the conversion to WSL2.

Cheers,
D.
