### ISSUE TITLE
Question: How to connect to xWSL RDP session via an iPad in WLAN?

### ISSUE THREAD

**Issue by vickunwu** [DesktopECHO/xWSL#18]
#### Desciption:
I was trying to import the .rdp file to my iPad but it seems not able to work. Anyone has some clue?

**Comment by DesktopECHO** [comment]
Hi, 

Just want to confirm -- Does the .rdp file work ok when you run it on your desktop?

I don't think you will be able to connect via your iPad because of the way networking is set up in WSL2.  The WSL2 virtual machine is NAT'ed behind your host system, so can only connect to xWSL via your local machine.  

WSL1 on the other hand, will not exhibit this issue.

**Comment by vickunwu** [comment]
Yes, the .rdp file works fine after I added the "-xWSL.local" as the instruction told. 
And I would try out on WSL1, but do you think it will work on WSL2 after I set up some sort of "Port Forwarding" on Windows?

**Comment by DesktopECHO** [comment]
This will work:

WSL2-PortForward.cmd

`@ECHO OFF`
`NETSH INTERFACE PORTPROXY RESET`
`SET LXDISTRO=xWSL & SET WSL2PORT=3399 & SET HOSTPORT=3398`
`WSL -d %LXDISTRO% -- ip addr show eth0 ^| grep -oP '(?^<=inet\s)\d+(\.\d+){3}' > IP.TMP`
`SET /p IP=<IP.TMP & NETSH INTERFACE PORTPROXY ADD v4tov4 listenport=%HOSTPORT% listenaddress=0.0.0.0 connectport=%WSL2PORT% connectaddress=%IP%`
`NETSH AdvFirewall Firewall add rule name="%LXDISTRO% Port Forward" dir=in action=allow protocol=TCP localport=%HOSTPORT% > NUL`
`ECHO WSL2 Virtual Machine %IP%:%WSL2PORT%now accepting traffic on %COMPUTERNAME%:%HOSTPORT%`  

Run the command:

`C:\>WSL2-PortForward.cmd`

Output:

`WSL2 Virtual Machine 172.17.109.95:3399 now accepting traffic on MYCOMPUTER:3398`

**Comment by DesktopECHO** [comment]
NOTE:  Based on my testing, WSL2 Performance is much worse than WSL1 in this scenario.
