### ISSUE TITLE
RDP gets stuck when logging in

### ISSUE THREAD

**Issue by TheArcaneBrony** [DesktopECHO/xWSL#20]
RDP session freezes when you log in

https://user-images.githubusercontent.com/13570458/109535688-239f9280-7abd-11eb-8b93-4710ca6468e9.mp4

**Comment by DesktopECHO** [comment]
Hi there, it's weird to see that RDP console... it shouldn't appear because the script is supposed to save the password in your RDP file.  Try uninstalling Kali and relaunching the script, perhaps try using a simpler password.  If the simpler password works it's a bug I will need to fix asap.

**Comment by DesktopECHO** [comment]
Also - I see you using port :1234 -- try something higher like :13389

**Comment by DesktopECHO** [comment]
If your Kali install already has more than one user created (past the original sudo user) I see where that might be a problem too.  Fixing...

**Comment by TheArcaneBrony** [comment]
i'm not using another user, its the one i specified during xWSL setup. Logging in as root causes the same hangup

**Comment by DesktopECHO** [comment]
Sorry mate I thought this was a bug against Kali-xRDP.  My bad. Let me see if I can recreate...

**Comment by TheArcaneBrony** [comment]
also, the rdp file it creates doesn't seem to work, hence the custom port
is it normal the 2 batch files that live in your xWSL directory are empty?

**Comment by DesktopECHO** [comment]
The RDP file should work every time.  Can you post the contents of your xWSL folder?  Is there a \logs folder?

**Comment by TheArcaneBrony** [comment]
I'm in the process of reinstalling xWSL right now, since it might have been since i had a custom path (which I don't see how i pulled that of)

**Comment by TheArcaneBrony** [comment]
Update: after reinstalling it works fine, might have been the installation path not being C:\xWSL,

**Comment by DesktopECHO** [comment]
So I tried installing to ```C:\Program Files``` 
No issue there...

    [xWSL Installer 20201229]

    Enter a unique name for your xWSL distro or hit Enter to use default.
    Keep this name simple, no space or underscore characters [xWSL]: Demo
    Port number for xRDP traffic or hit Enter to use default [3399]: 43399
    Port number for SSHd traffic or hit Enter to use default [3322]: 43322
    Set a custom DPI scale, or hit Enter for Windows default [1.5]:
    [Not recommended!] Type X to eXclude from Windows Defender:  
                                  
    Installing xWSL Distro [Demo] to "C:\Program Files\Demo"
    This will take a few minutes, please wait...

    [17:11:38] Installing Ubuntu 20.04 LTS (~1m00s)
    [17:12:05] Git clone and update repositories (~1m15s)
    [17:13:00] Remove un-needed packages (~1m00s)
    [17:13:33] Configure apt-fast Downloader (~0m15s)
    [17:13:49] Remote Desktop Components (~4m45s)
    [17:19:44] XFCE 4.16 (~2m00s)
    [17:23:44] Install Mozilla Seamonkey and media playback (~1m30s)
    [17:25:37] Post-install clean-up (~0m45s)
    
    Enter name of primary user for Demo: demo
    Enter password for demo: ****
    
    Open Windows Firewall Ports for xRDP, SSH, mDNS...
    Building RDP Connection file, Console link, Init system...
    Building Scheduled Task...
    SUCCESS: The scheduled task "Demo" has successfully been created.
    
          Start: Mon 03/01/2021 @ 17:11
            End: Mon 03/01/2021 @ 17:25
       Packages: 997
    
      - xRDP Server listening on port 43399 and SSHd on port 43322.

      - Links for GUI and Console sessions have been placed on your desktop.

      - (Re)launch init from the Task Scheduler or by running the following command:
        schtasks /run /tn Demo

     Demo Installation Complete!  GUI will start in a few seconds...
