### ISSUE TITLE
A need to reset without uninstalling/reinstalling the distro, and XFCE. 

### ISSUE THREAD

**Issue by RyanBjork1** [DesktopECHO/xWSL#21]

**Comment by DesktopECHO** [comment]
Hi can you be clearer in what you're asking for?
Thanks,
D.

**Comment by KushalSM** [comment]
I think he means that he wants to reset everything without removing and uninstalling the distro from the script

**Comment by DesktopECHO** [comment]
This is accomplished with LxRunOffline.exe -- After you install xWSL, use LxRunOffline to back-up the distro.  Then you can delete the distro and restore from backup as many times as you like.
