### ISSUE TITLE
Pulseaudio not working with VcXSrv

### ISSUE THREAD

**Issue by sakutty** [DesktopECHO/xWSL#22]
Okay so I don't know if you have any support for this but I will ask here.
So RDC has a lot of lag for me and VcXSrv is a lot smoother and easier to work on I converted it to WSL2 with minimal issues which I fixed but after I got VcXSrv to work it had no audio coming from PulseAudio while RDC still did I have tried the guide's online but they all need to run a executable wsl application (default is ubuntu.exe but its interchangable for all distros)  and I can't find xWSL's exe so I could do the same and passthrough audio , anyone have the same issue? Using RDP is a pain and its very laggy
I have attached the script to the pulseaudio bat file.
[startWSLVcXsrv.txt](https://github.com/DesktopECHO/xWSL/files/6290912/startWSLVcXsrv.txt)

(also i looked at the script and saw it was running 20.04 and changed it to ubuntu 2004 but it still did not work)

**Comment by DesktopECHO** [comment]
Hello,
This has nothing to do with xWSL.  
Closing.
