### ISSUE TITLE
GPG keys not found

### ISSUE THREAD

**Issue by themarceldekoster** [DesktopECHO/xWSL#28]
Tried today to make it work, also needed to add proxy capability. But gpg keys are not found when using apt-key for all 3 scripted keys.

**Comment by DesktopECHO** [comment]
Might be something to do with your internet connection/proxy.  I just spun the installer on a lab machine and I’m not seething any issues whatsoever. 

Unfortunately I don’t have a proxy server to test your scenario.  It should be able to be made to work, but I can’t get anymore specific than that… good luck!

**Comment by themarceldekoster** [comment]
ok, thx for checking. I am indeed behind proxy

**Comment by themarceldekoster** [comment]
proxy issue it seems
