### ISSUE TITLE
Multiple monitors with different resolutions

### ISSUE THREAD

**Issue by apreg** [DesktopECHO/xWSL#29]
Hi,

first I'd like to thank you for your hard work. It helped me a lot. One thing bothers me though. I have a monitor with a resolution of 3840x2160, scale 250% and another one 1920x1080, scale 100%. My host is a Windows 10 and I'm using the standard Remote Desktop client with "Use all my monitors for the remote session" on. The problem is when I log into ubuntu the scaling remains 1 on the 4K display resulting tiny fonts, icons etc. Do you have an idea for that?

**Comment by DesktopECHO** [comment]
Hi there, thank you for the kind words.  

Unfortunately, I'm not aware of a way to set custom DPI for separate displays in xRDP.  If I discover a way accomplish this I'll update this issue report.
