### ISSUE TITLE
Install was successful, but no desktop icons were created 

### ISSUE THREAD

**Issue by closertotheheart** [DesktopECHO/xWSL#3]
Install was successful, but no desktop icons were created.

Computer was rebooted, have logged in again.

No icons / shortcuts on desktop.

How do I manually launch RDP with the right settings / recreate the shortcuts?

running remote desktop connection to <hostname> produces the error:

"Your computer could not connect to another console session on the remote computer because you already have a console session in progress."

**Comment by closertotheheart** [comment]
Date search on filesystem turned up:

C:\Windows\System32\xWSL\xWSL-Init.cmd

to start things off and 

C:\Windows\System32\xWSL\xWSL.rdp

to attach via RDP.

**Comment by DesktopECHO** [comment]
Thank you for documenting this!
