### ISSUE TITLE
consistently crashes

### ISSUE THREAD

**Issue by jessewriter** [DesktopECHO/xWSL#31]
really cool project as setting this up is a real pia and i was able to see a graphical linux desktop.  unfortunately it would only stay open for a few mins before crashing.

win11 16gb ram wsl2

sorry i don't have any more useful info, might be sophos security blocking services idk

**Comment by DesktopECHO** [comment]
Hi I've been away for awhile.  Just following up on this, are you still working with it?
The crashes you're having -- What do you mean, is your RDP session dieing or something else?

**Comment by DesktopECHO** [comment]
Forgot to mention, you should be on Windows 11 22H2 to [avoid an intermittent BSOD](https://github.com/microsoft/WSL/issues/7480).
