### ISSUE TITLE
There is a WSL distribution registered with that name; uninstall it or choose a new name.

### ISSUE THREAD

**Issue by BrandonStudio** [DesktopECHO/xWSL#37]
Error occurs no matter what name I typed

**Comment by DesktopECHO** [comment]
What version of Windows are your running?
Are you usng the version of WSL included with the OS or the one from the Microsoft Store?

**Comment by DesktopECHO** [comment]
Not sure what's wrong with your setup.  Any funny characters in your install path?  

I was curious if xWSL worked on Windows Server 2022 Core as I've never tested that particular OS variant.  
No problems on a clean install in Azure, see below:

![image](https://github.com/DesktopECHO/xWSL/assets/33142753/fb5c5e74-69b9-45bb-a43b-126e91635ab8)

One thing to note even if you get it working in WSL1, there's a bug in Server 2022 that causes an intermittent [BSOD](https://github.com/microsoft/WSL/issues/7480).  The work-around would be to install WSL2 and convert the instance.

**Comment by DesktopECHO** [comment]
Per my message above I successfully ran the xWSL installer in an Azure instance of Server Core 2022 just a few minutes ago, per the screenshot I attached.

Once the instance is installed, the BSOD comes later, very randomly.

**Comment by DesktopECHO** [comment]
Don't know what to tell you, as you can see it worked fine for me.

The exact steps I took were:

- Spin-up a new Server Core 2022 Instance in Azure
- RDP into Server Core insance
- Download and launch the xWSL.cmd Installer. 
- The installer will notice the WSL role is not installed, so it will install WSL and ask to reboot the server.
- After reboot, re-launch the installer.
- Wait a few minutes for install to complete
- Success!

![image](https://github.com/DesktopECHO/xWSL/assets/33142753/e6afbfae-063e-4cd8-9c19-6d919b19a837)

If you want to login to the WSL instance via RDP, you'll need FreeRDP for Windows as Server Core doesn't include MSTSC.EXE

**Comment by DesktopECHO** [comment]
This issue appears to be caused by [KB5026370 (OS Build 20348.1726)](https://support.microsoft.com/en-us/topic/may-9-2023-kb5026370-os-build-20348-1726-8c5dc605-d613-46ea-9232-1425cfc91d62)

`wusa /uninstall /kb:5026370`

After a reboot, WSL is working again in Server Core 2022
