### ISSUE TITLE
ping requires sudo privileges, ssh does not?

### ISSUE THREAD

**Issue by closertotheheart** [DesktopECHO/xWSL#4]
$ ping <host>
ping: socket: Operation not permitted
$ sudo !ping
sudo ping <host>
PING <host> (<IP>) 56(84) bytes of data.
64 bytes from <host> (<IP>): icmp_seq=1 ttl=63 time=30.1 ms
...
^C
--- <host> ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 30.143/56.413/108.356/31.514 ms
$ ssh <host>
The authenticity of host '<host> (<IP>)' can't be established.
ECDSA key fingerprint is SHA256:<KEY>.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '<host>,<IP>' (ECDSA) to the list of known hosts.
<user>@<host>'s password: 
Last login: Wed May 27 16:25:49 2020 from <otherhost>
[<user>@<host> ~]$

**Comment by DesktopECHO** [comment]
Hi there, you're better off using Windows ping which will provide better results:

```zero@CORE01:~$ uname -a
Linux CORE01 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
zero@CORE01:~$ ping localhost
ping: socket: Operation not permitted
zero@CORE01:~$ ping.exe localhost

Pinging CORE01 [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
zero@CORE01:~$
```

Extra kudos If your username is a Rush reference :)
