### ISSUE TITLE
High cpu usage from python script

### ISSUE THREAD

**Issue by darexinfinity** [DesktopECHO/xWSL#46]
This python script from xWSL runs almost daily and consumes a large amount of the CPU. Although I haven't used anything WSL-related in a long time and I don't have it on startup. I'm not sure why it's running but it's using up a lot of power (CPU fan runs stronger the entire time).

![wigs6rv5302d1](https://github.com/DesktopECHO/xWSL/assets/62077445/ddf403ba-c7a1-4e7d-98bd-7ef8b45e1d0a)
![ste54hka302d1](https://github.com/DesktopECHO/xWSL/assets/62077445/be84e2eb-9037-4043-85de-ddfc42b18422)

**Comment by DesktopECHO** [comment]
Hi, uninstall and reinstall the xWSL instance to see if the issue persists.
