### ISSUE TITLE
What is needed to uninstall xWSL?

### ISSUE THREAD

**Issue by AlikanakelaKarwowski** [DesktopECHO/xWSL#5]
Installed xWSL on a test computer, played around with it and installed it on my main computer. What all do I need to do to essentially uninstall xWSL from the system?

**Comment by DesktopECHO** [comment]
Stop the LXSSManager service in Windows and use the bundled [LXrunoffline](https://github.com/DDoSolitary/LxRunOffline) binary to uninstall it, something like:

`LXrunoffline.exe ui -n xWSL`
