### ISSUE TITLE
Feature Request:  automatic setup google-chrome

### ISSUE THREAD

**Issue by jacksnodgrass** [DesktopECHO/xWSL#8]
Feature Request: install google-chrome

there are some wierid things you have to do to get google-chrome to work with wsl. 

I tried a few links / pages / sites / etc to get it setup and can't.  Would be nice if your configuration script would do this for me automatically / automagically. 

- jack

**Comment by DesktopECHO** [comment]
For a few reasons Chrome and Firefox will likely never work well in WSL1.  
Mozilla Seamonkey does a good job as defaut browser.  Pale Moon may be another option.
